### ISSUE TITLE
Failed to create PVC with the sample yaml

### ISSUE THREAD

**Issue by stonezdj** [pivotal-cf/docs-pks#1007]
link:
https://docs.pivotal.io/pks/1-6/volumes.html

![Screen Shot 2019-12-31 at 10 45 33 AM](https://user-images.githubusercontent.com/2696760/71608253-d07d3780-2bba-11ea-928c-19f0eb293c3a.png)

the indent of `requests:` is incorrect

**Comment by mnichols62** [comment]
Documentation and screenshots in this section refers to hostswitch1 and hostswitch2. Later on in the procedures to create edge transport nodes and preparing the host transport nodes, the values need to be n-vds-overlay and n-vds-vlan for the procedures to work.

**Comment by pspinrad** [comment]
Thanks @stonezdj -- fixed that indent.
