### ISSUE TITLE
Documentation for Transport Zones refers to hostswitch1 and hostswitch2

### ISSUE THREAD

**Issue by mnichols62** [pivotal-cf/docs-pks#1008]
Documentation and screenshots in this section refers to hostswitch1 and hostswitch2. Later on in the procedures to create edge transport nodes and preparing the host transport nodes, the values show are different and need to be n-vds-overlay and n-vds-vlan here for the procedures to work.

**Comment by pspinrad** [comment]
Thanks @mnichols62 -- just to confirm, issue is that, for example, https://docs.pivotal.io/pks/1-6/nsxt-2-5-installation-create-tzs.html and https://docs.pivotal.io/pks/1-6/nsxt-install-create-tzs.html use **N-VDS Name** values of `hostswitch1` and `hostswitch2`
...but https://docs.pivotal.io/pks/1-6/nsxt-2-5-installation-prepare-esxi-hosts.html#prep-esxi-configure and shows **N-VDS Name** as `N-VDS-OVERLAY`?
(Whereas https://docs.pivotal.io/pks/1-6/nsxt-install-prep-esxi-hosts.html#prep-esxi-configure  shows **N-VDS-Name** as `hostswitch1`, as it should.) 
@lparis any names we need to change?  Thanks!

**Comment by lparis** [comment]
Yes, the name needs to be updated to match. I will do this tomorrow. Thanks for bringing it to my attention.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On January 8, 2020 at 10:35:50 AM PST, Paul Spinrad <notifications@github.com> wrote:

Thanks @mnichols62<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmnichols62&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500470412&sdata=ufkVJ%2Fm7QCyL4AOXTJVYFVl7ZAGiljA4Egou0IMoqnE%3D&reserved=0> -- just to confirm, issue is that, for example, https://docs.pivotal.io/pks/1-6/nsxt-2-5-installation-create-tzs.html<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.pivotal.io%2Fpks%2F1-6%2Fnsxt-2-5-installation-create-tzs.html&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500480400&sdata=4G7kkx%2B1X%2BvwdNN6%2Fs0bXiFdMVqe9CeGnZKvuYAmMpY%3D&reserved=0> and https://docs.pivotal.io/pks/1-6/nsxt-install-create-tzs.html<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.pivotal.io%2Fpks%2F1-6%2Fnsxt-install-create-tzs.html&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500480400&sdata=22de3YAB883hTr41DYEmRoZ7vsBxvLuhKUPFJ2YiA2Q%3D&reserved=0> use N-VDS Name values of hostswitch1 and hostswitch2
...but https://docs.pivotal.io/pks/1-6/nsxt-2-5-installation-prepare-esxi-hosts.html#prep-esxi-configure<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.pivotal.io%2Fpks%2F1-6%2Fnsxt-2-5-installation-prepare-esxi-hosts.html%23prep-esxi-configure&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500490395&sdata=SZtpjoJF3omybDvxqiWnCtgRD%2BBpxQnPxQrjxAF%2Br28%3D&reserved=0> and shows N-VDS Name as N-VDS-OVERLAY?
(Whereas https://docs.pivotal.io/pks/1-6/nsxt-install-prep-esxi-hosts.html#prep-esxi-configure<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.pivotal.io%2Fpks%2F1-6%2Fnsxt-install-prep-esxi-hosts.html%23prep-esxi-configure&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500490395&sdata=WPlahyCcr%2B35P5ZhKhrSxJFOPcsqEkQt%2FWgPZnUDIO4%3D&reserved=0> shows N-VDS-Name as hostswitch1, as it should.)
@lparis<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flparis&data=02%7C01%7Clparis%40vmware.com%7C7ad5e68c4bc4455bf51f08d7946994dc%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637141053500500389&sdata=BKyV9HzET5Si%2BKEXHoXffszanNc7DqjHOLGENSYoyHM%3D&reserved=0> any names we need to change? Thanks!

**Comment by pspinrad** [comment]
Great-- thanks @lparis !

**Comment by lparis** [comment]
Addressed and merged. https://github.com/pivotal-cf/docs-pks/pull/1010
