### ISSUE TITLE
Helm init command instructions appear invalid

### ISSUE THREAD

**Issue by adamfowleruk** [pivotal-cf/docs-pks#1017]
On my machine (!) the helm init instruction here:
https://github.com/pivotal-cf/docs-pks/blob/1.6/helm.html.md.erb

Renders this response:
Error: unknown flag: --service-account

Perhaps the instructions need updating for the modern version of helm?

Email me internally too if required at afowler@pivotal.io

**Comment by pspinrad** [comment]
Thanks @adamfowleruk -- just followed up via email

**Comment by pspinrad** [comment]
Added distinction between Helm 2 and Helm 3, and linked to bitnami instrux for install Helm 3 - https://docs.pivotal.io/pks/1-6/helm.html
