### ISSUE TITLE
PKS on Azure docs clarifications

### ISSUE THREAD

**Issue by sudhakarau1** [pivotal-cf/docs-pks#1055]
From https://docs.pivotal.io/pks/1-6/installing-pks-azure.html
1. "enter the FQDN that you registered to point to the PKS API load balancer, such as api.pks.example.com. To retrieve the public IP address or FQDN of the PKS API load balancer, see the terraform.tfstate file." 
Q: what value from terraform.tfstate?
2. Default Security Group :"The name of the security group attached to the cluster's subnet"
Q: Which security group created by Terraform? There are 5:
-bosh-deployed-vms-security-group
-ops-manager-security-group
-pks-api-sg
-pks-internal-sg
-pks-master-sg
3. In Enter Primary Availability Set. "erraform creates this availability set and its name is YOUR-ENVIRONMENT-NAME-pks-as"
Q. The actual name created is ENVIRONMENT-NAME-availability-set so is doc incorrect?

**Comment by ograves-pivotal** [comment]
Hello @sudhakarau1 .  Thank you.
We're revisiting this request as part of removing all terraform references. You can see the changes for these particular terraform references here:

Known Issue: Azure Default Security Group Is Not Automatically Assigned to Cluster VMs:
 - TKGI v1.10: https://docs-pcf-staging.cfapps.io/tkgi/1-10/release-notes.html#security-group

Kubernetes Cloud Provider: Default Security Group and Primary Availability Set:
 - TKGI v1.10: https://docs-pcf-staging.cfapps.io/tkgi/1-10/installing-azure.html#cloud-provider

This rewording has been revised in TKGI v1.8 - TKGI v1.10 documentation.

Other terraform references will be removed on other tickets.
