### ISSUE TITLE
Documented DFW rules are incorrect

### ISSUE THREAD

**Issue by SDBrett** [pivotal-cf/docs-pks#1062]
DFW rules generated when deploying a K8S cluster through PKS 1.6 do not match the documented  `hc-pks-UUID-Section` rules.

CoreDNS Rule:
**Documentation:** `Source=Kubernetes worker node (hosting the DNS Pod); Destination=DNS Pod IP; Port: TCP/8081 and TCP/10054; Action: allow`

**Actual:** `Source=Kubernetes worker node (hosting the DNS Pod) IP Address; Destination=Any; Port: TCP/8080; Action: allow, Applied to CoreDNS pod logical port`
 

Validator Rule:
**Documentation:** Not documented

**Actual:** `Source=Kubernetes worker node (hosting the DNS Pod) IP Address; Destination=Any; Port: TCP/9000; Action: allow, Applied to Validator pod logical port`

The Dashboard rule created matches documented rule.

**Comment by pspinrad** [comment]
Incorporated suggestion: https://docs.pivotal.io/pks/1-6/vsphere-nsxt-cluster-objects.html#nsxt-dfw

Cherry-picked to other versions, and tweaked wording for v1.7 and later, which don't install Dashboard by default
