### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lparis** [pivotal-cf/docs-pks#1091]
Broken link scan run May 2nd in the evening. Docs deployed to docs.vmware.com based on pull of PKS github repos on that same date.

Harbor OSS docs moved here: https://goharbor.io/docs/1.10/. 

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/pivotal-cf/kubo-odb-ci/blob/master/specs/dex.yml in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-k8s-profiles-dex-oidc.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-NSX-T/2.4/com.vmware.nsxt.admin.doc/GUID-46C7B20D-4BE4-400E-AF39-1ADFE945DE38.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-nsxt-create-objects.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1/csinodes/3a0ea98b-879e-4f7a-abbd-e3ad426c8a1b in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://csi.vsphere.vmware.com/ in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1/csinodes/c4e3819f-00fc-457b-beda-26fbdd589c53 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1/csinodes/c9b4f441-4c08-43cf-bb17-8be80ed676a4 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://csi.vsphere.vmware.com/ in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://csi.vsphere.vmware.com/ in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://csi.vsphere.vmware.com/ in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://kubectl.kubernetes.io/last-applied-configuration in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1 in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL http://storage.k8s.io/v1beta1/csidrivers/csi.vsphere.vmware.com in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.7/vmware-enterprise-pks-17/GUID-vsphere-cns.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/patch-console-components.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/deploy-ent-pks-wizard.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/upgrade-console.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/console-troubleshooting.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-console/console-login-opsmanager.html in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/rn/VMware-Enterprise-PKS-16-Release-Notes.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#role-based-access-controlrbac in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#managing-projects in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#pulling-and-pushing-images-using-docker-client in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#manage-helm-charts in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#administrator-options in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.6/vmware-enterprise-pks-16/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#role-based-access-controlrbac in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#managing-projects in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#pulling-and-pushing-images-using-docker-client in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#manage-helm-charts in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

We ran our weekly check of docs.vmware.com and found a broken URL https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#administrator-options in your publication on page https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-enterprise-pks-15/GUID-harbor.html Fix or remove the link, and republish your document all the way to production.

**Comment by ograves-pivotal** [comment]
Hello there @lparis 
Lorenzo, I've fixed the links that were bad links (or shouldn't even have been links) in the PKS docs.

There are several links that were not problems in our PKS repo but are bad links when on the VMware site.  Is there anything I can do in the PKS docs so that the VMware site links are valid?:
 - ./console/patch-console-components.html
 - /pks/1-6/console/deploy-ent-pks-wizard.html
 - /pks/1-6/console/upgrade-console.html
 - /pks/1-6/console/console-troubleshooting.html
 - /pks/1-6/console/console-login-opsmanager.html

Thanks!
 (cc: @stuclem )

**Comment by lparis** [comment]
Thanks. We have redeployed on our end and will do so again on Friday to stay consistent with the schedule. Then we will see what the link checker has to say. Let's close this out and open a new one as needed. Thanks for doing this.

**Comment by stuclem** [comment]
Hi Ollie,

I fixed these just now. The issue arises because our MD-to-vmware.docs converter replaces the backslash after folder names with a hyphen. So, in the VMware version, links to, for example, /pks/1-6/console/deploy-ent-pks-wizard.html get converted to /pks/1-6/console-deploy-ent-pks-wizard.html.

I am just publishing the update to docs.vmware.com now.

Thanks!
s

--
Stuart Clements
Modern Applications Platform documentation
