### ISSUE TITLE
infrastructure_networks for share-t1 on multi-t0 is missing from 1.6 and 1.7 docs

### ISSUE THREAD

**Issue by lparis** [pivotal-cf/docs-pks#1139]
Looks like it was lost during the refactoring: https://docs.pivotal.io/pks/1-5/network-profiles-shared-t1.html#shared-t1-multi-t0. Can't find this in the 1.6 and 1.7 docs.

See https://vmware.slack.com/archives/C8DJ383EX/p1591691223079800

**Comment by pspinrad** [comment]
Thanks @lparis - restored that section in 1.6+ versions.
