### ISSUE TITLE
Dropdown for 1.8 not workin

### ISSUE THREAD

**Issue by Salamandastron1** [pivotal-cf/docs-pks#1159]
I assume the link is broken but selecting 1.8 from the drop-down always directs to 1.5

**Comment by vikafed** [comment]
Thanks for letting us know, @Salamandastron1! Can you share a bit more background on this problem -- what page are you on when selecting 1.8 from the dropdown and what page are you trying  to access?

**Comment by pspinrad** [comment]
The PKS 2.5 docs have NSX-T v2.4 setup instrux with filenames that begin with `nsxt-install-`.  Later PKS version docs don't  have these topics, so they had a redirect to the v2.5 docs:
>  r301 %r{/tkgi/1-8/nsxt-install-(.*)}, “/pks/1-5/nsxt-install-$1"

I removed this redirect so users won't get bounced back to v1.5, which is no longer supported.
