### ISSUE TITLE
PKS 1.8 Documentation - Change recommendation to a single NVDS to NSX-T Edges

### ISSUE THREAD

**Issue by kalenarndt** [pivotal-cf/docs-pks#1169]
In the section - Create Transport Zones

> "However, the default TZs cannot be used by TKGI. If you do use them, you will receive an pks-nsx-t-osb-proxy BOSH error when you try to deploy TKGI."

Working with Francis internally we have tested using the default transport zones and as long as you specify the nvds name on the NSX-T Edge to be the same that is defined on the default transport zones (nsxHostSwitch) then you wont receive the BOSH error when you deploy TKGI.  This would allow us to continue recommending the practice of a single n-vds design so we can leverage multi-tep in production. 

This would remove the need for the creation of a TEP port group in the following steps and you would need to add additional steps for creating another trunk port group. 

1.  Create EDGE-UPLINK-PG-A (VLAN TRUNK) with vmnic0 as active and vmnic1 as standby
2.  Create EDGE-UPLINK-PG-B (VLAN TRUNK) with vmnic1 as active and vmnic0 as standby

We should also add a section on the creation of uplink profiles to support multi-tep and a single-nvds design. This would include the creation of custom failover teaming policies as well as setting up the vlan tag and MTU for the TEP interfaces for the compute hosts as well as the edges.  https://communities.vmware.com/docs/DOC-37591 (Page 26) 

We would also want to cover setting up a Transport Node Profile as a part of the workflow since the recommendations for AZs are generally based on cluster boundaries and to ensure consistent configuration on the TNs within a cluster we leverage these in standard engagements. 

Please reach out if you have any questions.

**Comment by lparis** [comment]
Thanks. Working on this.

**Comment by lparis** [comment]
This PR addresses most of what is in this issue: https://github.com/pivotal-cf/docs-pks/tree/address-issue-1169. Still need to follow up on the port groups.

**Comment by lparis** [comment]
this is addressed here: https://docs.pivotal.io/tkgi/1-9/nsxt-3-0-install.html#configure-the-n-vds-switch
closing as fixed
@kalenarndt please review and open new issue if anything is amiss, thanks
