### ISSUE TITLE
TKGI 1.8 with NSX-T Firewall Ports & Protocol : Documentation update request

### ISSUE THREAD

**Issue by prarup13** [pivotal-cf/docs-pks#1242]
Hello Team,
As per the below document of firewall ports and protocol requirement, one key port requirement is missing in documentation ,
https://docs.pivotal.io/tkgi/1-8/ports-protocols-nsx-t.html

During one of the implementation found out I was not able to prepare ESXi host with NSX-T , was getting below error  , 

Later after spending hours troubleshooting understand that from esxi vmknic/edge nodes to NSX-T manager port 1234 (NSX messaging) is to be opened , and the issue was resolved.
 
Details of firewall requirement for NSX-T can also be found on the below link
https://ports.vmware.com/home/NSX-T-Data-Center

Attached is the NSX-T Firewall port requirements and the error snapshots 

Kindly update the document to include from ESXI & EDGE Transport Nodes to NSX Manager port 1234 is also required .

Thanks
Prashant
![NSX-T error](https://user-images.githubusercontent.com/71909486/94325409-cfa1f680-ffd0-11ea-9a70-e9c986e9805b.jpg)
[vmware_ports (1).xlsx](https://github.com/pivotal-cf/docs-pks/files/5285911/vmware_ports.1.xlsx)

**Comment by lparis** [comment]
this is addressed, closing
