### ISSUE TITLE
kube-prometheus/rules/windows.libsonnet mixin rules path has changed

### ISSUE THREAD

**Issue by perithompson** [pivotal-cf/docs-pks#1283]
https://github.com/pivotal-cf/docs-pks/blob/b72278294125312e4bdaeda366af009320e06e61/windows-monitoring.html.md.erb#L121
The path for the kube-prometheus rules have now changed and the manifests no longer compile when copying the and modifying the path in the mixin directory

https://github.com/prometheus-operator/kube-prometheus/commit/e556dbfd88a963c73159246b950b75193d72d800

After following the instructions and moving the windows.libsonnet to the new path I get the following error

```
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests examples/kustomize.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
RUNTIME ERROR: No such field: wmiExporterSelector
        <std>:756:15-42 thunk <val> from <function <format_codes_obj>>
        <std>:761:27-30 thunk from <thunk <s> from <function <format_codes_obj>>>
        <std>:585:22-25 thunk from <function <format_code>>
        <std>:585:9-26  function <format_code>
        <std>:761:15-50 thunk <s> from <function <format_codes_obj>>
        <std>:766:24-25 thunk from <thunk <s_padded> from <function <format_codes_obj>>>
```

**Comment by ograves-pivotal** [comment]
@perithompson, based on the slack thread, I think the best we can do from here in documentation is to link to "latest" rather than the master branch. I will make the needed edits for the links to kube-prometheus and kubernetes-mixin in the next few minutes.

Thanks.
