### ISSUE TITLE
What minimal service account permissions are needed for GCP service accounts?

### ISSUE THREAD

**Issue by ctaymor** [pivotal-cf/docs-pks#131]
The two pages https://docs.pivotal.io/runtimes/pks/1-0/gcp-requirements.html and https://docs.pivotal.io/runtimes/pks/1-0/installing-pks-gcp.html link to each other circularly and each imply that the other will tell you more but neither tells you the permissions the service account needs.

We should add the list of permissions needed, probably on the gcp-requirements page.

**Comment by mjgutermuth** [comment]
We've updated the service account steps a lot since this issue was filed -- I think this is resolved, but if you disagree @ctaymor let me know and I'll reopen. Thanks!
