### ISSUE TITLE
Docs should use lower-case input here

### ISSUE THREAD

**Issue by dyozie** [pivotal-cf/docs-pks#168]
https://github.com/pivotal-cf/docs-pks/blob/a358982d858201014d4e8783d6a03de53a62482b/gcp-prepare-env.html.md.erb#L63

Network names need to be lower-case.  If you type in "MY-PKS-virt-net" as instructed it errors with *Name must be lowercase letters, numbers, and hyphens*

**Comment by scribblingfox** [comment]
Hey @dyozie, thanks for calling this out! I updated this example and added a note to clarify that network names must be lower case.
