### ISSUE TITLE
Correct UI

### ISSUE THREAD

**Issue by dyozie** [pivotal-cf/docs-pks#169]
https://github.com/pivotal-cf/docs-pks/blob/1d762611d95478c0bf4504266eb049d7b7d0f2c8/gcp-prepare-env.html.md.erb#L249

Firewall Rules also appears under **VPC network**.  There is no **Networking** pane.

**Comment by mjgutermuth** [comment]
Thanks @dyozie! I've updated the docs to reflect this.
