### ISSUE TITLE
Manage Users -  wrong ordering of steps

### ISSUE THREAD

**Issue by leeloodub** [pivotal-cf/docs-pks#187]
On the https://docs.pivotal.io/runtimes/pks/1-0/manage-users.html page, the `Retrieve UAA Admin Credentials` step comes after `Log in as an Admin`.

However, the steps should be reversed as we need the credentials before we can login. step 5 of `Log in as an Admin` actually references that fact.

**Comment by scribblingfox** [comment]
Hey @leeloodub, thanks so much for this PR! I'm making the changes you suggested now, and clarifying the text a bit more while i'm here. :)
