### ISSUE TITLE
UAA Admin Credentials wrong 

### ISSUE THREAD

**Issue by leeloodub** [pivotal-cf/docs-pks#188]
On the https://docs.pivotal.io/runtimes/pks/1-0/manage-users.html page, under the `Retrieve UAA Admin Credentials` heading, step 3 points to ` Uaa Admin Secret` from the tile to get the admin client credentials.

Today in the tile for 1.0 it is actually called `Pks Uaa Management Admin Client`

**Comment by scribblingfox** [comment]
Hey @leeloodub, thanks for this PR! The step you corrected was a little unclear in other ways, so I updated the name and also clarified the action for the user to take. Thanks again!

**Comment by neil-hickey** [comment]
hey @scribblingfox I think we made a mistake, this should be the updated value on edge branch not master. Master should still say `Uaa Admin Secret`

**Comment by mjgutermuth** [comment]
Hey @neil-hickey and @leeloodub this got detached from the tracker story, but we did revert the change on master so the credential name should be correct now: https://docs-pcf-staging.cfapps.io/runtimes/pks/1-0/manage-users.html#uaa-admin

Thanks!
