### ISSUE TITLE
Update release notes for 1.0.2

### ISSUE THREAD

**Issue by nmandaleeka** [pivotal-cf/docs-pks#189]
In the release notes documented here:  "https://docs.pivotal.io/runtimes/pks/1-0/release-notes.html#v1.0.2-upgrade" 
Please add the following step before step 6 ("_6. Follow the procedures in Upgrade PKS._")
6. Download the latest 3468.x stemcell and configure the PKS tile with the stem cell.

**Comment by scribblingfox** [comment]
Hey there @nmandaleeka thanks for this PR! I'm updating the release notes right now.
