### ISSUE TITLE
Preparing to Deploy PKS on GCP - Misleading steps

### ISSUE THREAD

**Issue by darshitsanghavi** [pivotal-cf/docs-pks#200]
https://docs.pivotal.io/runtimes/pks/1-0/gcp-prepare-env.html
https://github.com/pivotal-cf/docs-pks/blob/master/gcp-prepare-env.html.md.erb

Step 1 is for setting up an IAM Service Account and Step 2 is for enabling Google Cloud API.

The order of this steps shouldn't bother if the GCP account/project is not newly created. In case of a newly created GCP account, the Compute Engine roles don't show up unless the API is enabled under Step 2.

Step 2 should be swapped with Step 1

**Comment by scribblingfox** [comment]
Hi @darshitsanghavi, thanks for this PR! I'm switching those steps right now.

**Comment by mayureshkrishna** [comment]
Even though I do not have Compute Engine API enabled, I could see the roles. Though, switching the steps won't hurt.
![gceapi](https://user-images.githubusercontent.com/8810559/40132092-cf66c74c-5909-11e8-9ee4-04ecc091e1fe.png)
<img width="635" alt="saroles" src="https://user-images.githubusercontent.com/8810559/40132097-d5bd5214-5909-11e8-9954-f02b58969469.png">

**Comment by darshitsanghavi** [comment]
Try creating a new project and navigate to service account you should able to see my observation or try it on a freshly created gcp account

**Comment by seviet** [comment]
We've switched the steps in the docs.
