### ISSUE TITLE
Resource Config refers to Load Balancer in vSphere

### ISSUE THREAD

**Issue by ntdt** [pivotal-cf/docs-pks#201]
installing-pks-vsphere.html.md.erb refers to
`To modify the resource usage of PKS, click Resource Config and edit the PKS on-demand broker job.
If you created a PKS API load balancer, enter a name that begins with tcp: in the Load Balancers column. For example, tcp:pks-api.`

but I see no column Load Balancers in Ops Manager 2.0 with Pivotal Container Service with vSphere.

**Comment by scribblingfox** [comment]
Hi @ntdt , thanks for your PR on the PKS docs! I'm working on this right now, and we'll have it resolved soon. 

Best,

Sarah
