### ISSUE TITLE
Service Account Actor Role  Depricated

### ISSUE THREAD

**Issue by darshitsanghavi** [pivotal-cf/docs-pks#202]
The role mentioned in the document has been deprecated by GCP
https://github.com/pivotal-cf/docs-pks/blob/247e5cd86a91d4961df03c59ad3dcf8809e398f3/gcp-prepare-env.html.md.erb#L32

Ref: https://cloud.google.com/iam/docs/service-accounts#the_service_account_actor_role

**Comment by jasonmimick** [comment]
:+1: on fixing this - upvote
Hit this myself just now.

**Comment by mjgutermuth** [comment]
Thanks @darshitsanghavi! We've removed the reference to this role from the docs.
