### ISSUE TITLE
Roles Missing in the new role documentation

### ISSUE THREAD

**Issue by darshitsanghavi** [pivotal-cf/docs-pks#209]
Hi,

https://github.com/pivotal-cf/docs-pks/blob/247e5cd86a91d4961df03c59ad3dcf8809e398f3/gcp-prepare-env.html.md.erb#L26

In the roles mentioned Compute Viewer is missing. Earlier it was there for v1.0.2 where there was only one role for master as well as worker.

When the role is missing for Master, k8s cluster could be created, but k8s services like "kube-dns" has issue with bootstrapping hence throws error in creation.

Looking at the  kube-controller-manager logs, the missing google cloud service account privileges error is seen.

Thanks
Darshit Sanghavi

**Comment by mjgutermuth** [comment]
Thank you, @darshitsanghavi! We've added the missing role to the documentation in the following commit: https://github.com/pivotal-cf/docs-pks/commit/3bd9ab996eaae31190266df64b69ec63d1904deb
