### ISSUE TITLE
OpsManager and Bosh need to use the Master Node Service Account

### ISSUE THREAD

**Issue by jaimegag** [pivotal-cf/docs-pks#215]
In the section `Preparing to Deploy PKS on GCP` (Step 2: Create Service Accounts) you are advised to create two Service Accounts (for Kubernetes Master and Worker nodes). But you also need a Service Account for OpsManager and Bosh to use.

Preparing OpsManager in GCP 
https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-deploy.html.md.erb#L84
It links back to `Preparing to Deploy PKS on GCP`, but the link is broken. It should link to `Step 2: Create Service Accounts` and specify that the Service Account to use is the Master one.

Configuring Ops Manager in GCP
https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-config.html.md.erb#L84
It links back to `Preparing to Deploy PKS on GCP` (Step 2: Create Service Accounts) but it doesn't specify which Service account to use from the two that you are requested to create (Master and Worker). It should specify to use the Master one.

**Comment by animatedmax** [comment]
Hi @jaimegag We added the need for a BOSH / Ops Manager Service Account: 
https://docs.pivotal.io/runtimes/pks/1-0/gcp-prepare-env.html#create-bosh-ops-man

We also updated the information in https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-deploy.html.md.erb#L84 and https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-config.html.md.erb#L84

Thanks much
