### ISSUE TITLE
CF::UAA::NotFound: CF::UAA::NotFound Error

### ISSUE THREAD

**Issue by kumarganesh2814** [pivotal-cf/docs-pks#218]
Hi Team,

While trying to add a new user then providing access Getting Error like below 

CF::UAA::NotFound: CF::UAA::NotFound

ubuntu@pksopsmgr:~$ uaac user add alana --emails alana@example.com -p password
user account successfully added
ubuntu@pksopsmgr:~$ uaac member add pks.clusters.admin alana

CF::UAA::NotFound: CF::UAA::NotFound

Can you please suggest how to resolve this and 

Is there is a simple way to login to pks 

I am trying to follow doc 
https://docs.pivotal.io/runtimes/pks/1-0/create-cluster.html#cluster-access

But information provided there is very tidious. 

Please Share some simple steps I can do to Login : 

pks login -a PKS_API -u USERNAME -p PASSWORD --ca-cert CERT-PATH

Best Regards
Ganesh Kumar

**Comment by lusyoe** [comment]
same problem！
version：pivotal-container-service-1.0.4-build.5.pivotal

`uaac version`
UAA Client：4.1.0

**Comment by mjgutermuth** [comment]
Hi @kumarganesh2814 @lusyoe thanks for reaching out to us. We recommend that you contact Pivotal Support for help troubleshooting this issue. The docs team will follow up with Support to see if documentation changes are required. Thanks!
