### ISSUE TITLE
PKS 1.1 stemcell version wrong in the docs

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#238]
The stemcell version specified at https://github.com/pivotal-cf/docs-pks/blob/master/release-notes.html.md.erb#L63 is 3451.25, it should be 3541.25

**Comment by animatedmax** [comment]
Thank you, @outofmem0ry We have updated the topic to correct this issue. 
https://docs-pcf-staging.cfapps.io/runtimes/pks/1-1/release-notes.html
