### ISSUE TITLE
Google Cloud Config should refer to BOSH / Ops Manager Service Account and not Master

### ISSUE THREAD

**Issue by jaimegag** [pivotal-cf/docs-pks#239]
The Google Cloud Config section of the OpsManager Director tile is the configuration to be passed to Bosh to talk to the GCP API. We should use the BOSH / Ops Manager Service Account for this.
These two lines should be edited:
- https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-config.html.md.erb#L84
- https://github.com/pivotal-cf/docs-pks/blob/master/gcp-om-config.html.md.erb#L142

Where it says `master node service account` it should read `BOSH / Ops Manager Service Account`

**Comment by animatedmax** [comment]
Hi @jaimegag These have been corrected, thanks!
