### ISSUE TITLE
NSX Manager Super User Principal Identify Certificate

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#241]
Regarding the step for "NSX Manager Super User Principal Identify Certificate" under [Networking](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-1/installing-nsx-t.html#networking):
The referenced step for creating this Cert, [Step 6: Generate and Register Certificates](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-1/installing-nsx-t.html#certificates) is empty.    

What would be the procedure for this?

**Comment by mjgutermuth** [comment]
Thanks @kroberts7! This section has been updated: https://github.com/pivotal-cf/docs-pks/blob/0139f5fb65df4562607ad2a46631118f98f930a5/installing-nsx-t.html.md.erb#L335-L519
