### ISSUE TITLE
helm concourse guide should inform reader that privilieged containers are required

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pks#246]
Deploying the concourse chart will fail if privileged containers is not enabled.  The statefulset will display this event which is not particularly descriptive. 

```
:> kubectl describe statefulset my-concourse-worker
Warning  FailedCreate      1m (x36 over 11m)  statefulset-controller  create Pod my-concourse-worker-0 in StatefulSet my-concourse-worker failed error: Pod "my-concourse-worker-0" is invalid: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

A note like this in the procedure will be helpful

```
<p class="note"><strong>Note</strong>: Privileged containers must be enabled in the PKS plan for Concourse to function.  Refer to configuring [plans](https://docs.pivotal.io/runtimes/pks/1-1/installing-pks.html#plans) in the install guide for more information on enabling privileged containers.</p>
```

https://github.com/pivotal-cf/docs-pks/blob/14c053f957aa0ff573c7ee71a90065b95ccada64/concourse-helm.html.md.erb#L7

**Comment by mjgutermuth** [comment]
Thank you @randomtask1155! We've updated this document to include a note about enabling privileged containers: https://github.com/pivotal-cf/docs-pks/blob/0139f5fb65df4562607ad2a46631118f98f930a5/concourse-helm.html.md.erb#L10
