### ISSUE TITLE
Step 3: Upgrade NSX-T (Optional), not required while upgrading PKS

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#250]
Upgrade of NSX-T tile is not required as PKS never uses NSX-T tile. All the NSX-T configurations are embedded into PKS tile and configured there. https://docs-pcf-staging.cfapps.io/runtimes/pks/1-1/upgrade-pks.html

**Comment by lparis** [comment]
See https://www.pivotaltracker.com/story/show/158676406. Will be following up with Narayan.

**Comment by lparis** [comment]
I commented on the story.

**Comment by mjgutermuth** [comment]
Thanks @lparis!
