### ISSUE TITLE
pks-feedback@pivotal.io not exists

### ISSUE THREAD

**Issue by fenixam** [pivotal-cf/docs-pks#256]
We're writing to let you know that the group you tried to contact (pks-feedback) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

**Comment by mjgutermuth** [comment]
Hi @fenixam, thanks for pointing this out! We've adjusted the permissions for the feedback email account. Could you try sending another message to pks-feedback@pivotal.io and see if you still receive the error?

**Comment by papajulio** [comment]
Hello, @mjgutermuth   I just tried to email you there and I didn't have luck either. It keeps giving the same error than @fenixam reported

**Comment by fenixam** [comment]
Seems it is still not working:

Od: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
Do: amalinowski@hot.pl
Data: 2018-07-03 13:58
Temat: Delivery Status Notification (Failure)



We're writing to let you know that the group you tried to contact 
(pks-feedback) may not exist, or you may not have permission to post 
messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

Dnia 2018-07-03 13:00 Julio J. García Martín napisał(a):

>Hello, @mjgutermuth   I just tried to email you there and I didn't have 
luck either. It keeps giving the same error than @fenixam reported
>
>



-- 
Pozdrawiam,
Arkadiusz Malinowski

**Comment by mjgutermuth** [comment]
Hi @fenixam @papajulio could you try sending another email? Thank you for your patience with this!

**Comment by mjgutermuth** [comment]
I see your message @fenixam! Seems like it is working now.
