### ISSUE TITLE
Step 3 is asking to tag the PKS Control VM before it's created

### ISSUE THREAD

**Issue by asaikali** [pivotal-cf/docs-pks#266]
Following the steps at https://docs.pivotal.io/runtimes/pks/1-1/gcp-api-load-balancer.html Step 3 is asking that the PKS controller VM be tagger, but the PKS tile has not been imported yet so the VM has not yet been created.

**Comment by jaimegag** [comment]
+1
This wasn't like this in previous versions of the docs (extracted from the cookbook)
Step 3 (https://docs.pivotal.io/runtimes/pks/1-1/gcp-api-load-balancer.html#step-3:-create-a-network-tag-for-the-firewall-rule) can only happen after installing PKS.
It should be moved into Step 5 here: https://docs.pivotal.io/runtimes/pks/1-0/installing-pks.html#-step-5:-configure-external-load-balancer

**Comment by vikafed** [comment]
Hi @asaikali @jaimegag. We updated the Configuring a GCP Load Balancer for the PKS API and Installing and Configuring PKS topics:

- https://docs.pivotal.io/runtimes/pks/1-1/gcp-api-load-balancer.html#install

- https://docs.pivotal.io/runtimes/pks/1-1/installing-pks.html#loadbalancer-pks-api
