### ISSUE TITLE
Confusing GCP LoadBalancer Setup Instructions

### ISSUE THREAD

**Issue by asaikali** [pivotal-cf/docs-pks#267]
The instructions at https://docs.pivotal.io/runtimes/pks/1-1/gcp-cluster-load-balancer.html are very confusing for example the step titled "Creating GCP Load Balancers for PKS Clusters" in substep 8 wants the selection of worker nodes to picked but the tile has not been installed at this point there is no point. Seems like this whole page is in the wrong spot or has wrong instructions.

**Comment by mjgutermuth** [comment]
Hi @asaikali, thanks so much for this feedback! We've reorganized this topic to more accurately reflect the cluster load balancer creation process: https://docs.pivotal.io/runtimes/pks/1-1/gcp-cluster-load-balancer.html

Please let us know if you have additional feedback. Thanks again!
