### ISSUE TITLE
Service Network option is unavailable under "create network" section of opsman configuration

### ISSUE THREAD

**Issue by shausy** [pivotal-cf/docs-pks#269]
Using pcf-vsphere-2.1-build.326.ova for opsmanger deployment 

https://docs.pivotal.io/runtimes/pks/1-1/vsphere-om-config.html
Step 5: Create Networks Page

Doc says - Service Network	Leave Service Network unchecked for network creation 
but with the above mentioned build I don't see the option of "service network"

**Comment by bentarnoff** [comment]
@shausy Thanks for raising this issue. We've updated the docs to reflect the removal of the "Service Network" checkbox.
