### ISSUE TITLE
Step by step instructions for accessing the dashboard should be provided

### ISSUE THREAD

**Issue by asaikali** [pivotal-cf/docs-pks#277]
The docs refer to the user to the k8s docs to access the dashboard. This is confusing as the referenced docks will change over time it was not specifying a version of k8s in the link. Also the linked docs don't explain how to get the creds to access to the dashboard. It would much clearer if we provided a step by stop instructions that were tested with the version of pks that is included in the docs.

**Comment by vikafed** [comment]
@asaikali, thanks for letting us know!
