### ISSUE TITLE
In the upgrade instructions Step 2 and 3 should be merged

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#281]
Upgrade steps 2 and 3 should be merged under the upgrade instructions https://docs.pivotal.io/runtimes/pks/1-1/upgrade-pks.html. The reason behind that is NSX-T properties are configured as part of PKS tile. Step 2 requires the reader to Upgrade the PKS Tile and hit apply changes. However before hitting Apply Changes all the NSX-T properties should also be configured in order for the upgrade to be successful in NSX-T environment.

**Comment by outofmem0ry** [comment]
We can close this as this was addressed by - https://github.com/pivotal-cf/docs-pks/pull/282

**Comment by mjgutermuth** [comment]
Thanks @outofmem0ry!
