### ISSUE TITLE
Issues with PKS release notes

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#285]
- PKS 1.1.0 section is still there but the release is not available on Pivnet
- Minor Typo
>VMware NSX-T | 2.1 - Advanced Edition | **NST-T** versions supported for Pivotal Container Service (PKS)
- There is a single component version table for all three version PKS 1.1.0, 1.1.1 and 1.1.2 and the component version still states that the supported Opsmgr version is 2.1.0-2.1.6 which is not the case for publicly available releases as per Pivnet
- VMware Harbor Registry version compatible is 1.5.0 whereas there is no 1.5.0 release on Pivnet. I only see three versions publicly available 1.4.2, 1.5.1 and 1.5.2 out of which only 1.5.x is compatible with PKS 1.1.x

**Comment by bentarnoff** [comment]
Hey @outofmem0ry thanks for this. We've added "Product Snapshots" for each PKS v1.1.x version to clarify component and compatibility information. We've also added a warning box to the PKS v1.1.0 portion of the release notes topic to clarify that PKS v1.1.0 is no longer available from Pivotal Network. Take a look and please raise another issue if you have further feedback. Thanks! https://docs.pivotal.io/runtimes/pks/1-1/release-notes.html
