### ISSUE TITLE
Certificate import with NSX Manager

### ISSUE THREAD

**Issue by jerryhwg** [pivotal-cf/docs-pks#286]
https://docs.pivotal.io/runtimes/pks/1-1/installing-nsx-t.html#certificates-nsx-manager

Step 6.2.2: Register the Certificate with NSX Manager

Import the certificate by copying nsx.crt and nsx.key. For instructions, see Import a CA Certificate in the NSX-T documentation.

It should be "Import a Certificate".

**Comment by bentarnoff** [comment]
Hey @jerryhwang72, are you looking at https://docs.pivotal.io/runtimes/pks/1-1/generate-certificates.html#register-certificate? If so, I believe the title of the link "Import a CA Certificate" is correct, because that's the title of the linked VMware topic: https://docs.vmware.com/en/VMware-NSX-T/2.1/com.vmware.nsxt.admin.doc/GUID-4135E962-E3EE-4285-8A66-E54E43937AE9.html.

**Comment by bentarnoff** [comment]
Closing this for now. Please feel free to get in touch if you have any questions or concerns.

**Comment by jerryhwg** [comment]
The link is correct, however you are supposed to use "Import Certificate" instead of "Import a CA Certificate" to copy & paste "nsx.crt" and "nsx.key" for the specific task for Ops Manager.
So the vmware doc is correct and the link works, however it links to the incorrect doc for the specific task for Ops Manager. You will experience it if you actually perform the task. 
I had to ensure it in our internal wiki doc so my team people won't struggle with it.

**Comment by bentarnoff** [comment]
Thanks for this clarification, @jerryhwg. We'll make sure this gets updated.

**Comment by lparis** [comment]
@jerryhwg Please perform this action using the 1.2 docs, which have been updated: https://docs.pivotal.io/runtimes/pks/1-2/generate-nsx-pi-cert.html. Even if you are running/installing PKS 1.1.x, please use this set of instructions. Thanks.

**Comment by lparis** [comment]
This PR addresses Jerry's issue: https://github.com/pivotal-cf/docs-pks/pull/410/files. Sorry for the confusion Jerry. thanks

**Comment by seviet** [comment]
thanks @lparis! @jerryhwg if you are still running into issues, let us now.
