### ISSUE TITLE
Clarify vSphere Cluster Names option in PKS Tile

### ISSUE THREAD

**Issue by lparis** [pivotal-cf/docs-pks#287]
It is not clear in the docs what values the PKS Tile > Networking > *vSphere Cluster Names* option expects. The inline help in the UI says "Enter the list of vSphere cluster names (comma separated) where kubernetes clusters will be deployed." The documentation says (https://docs.pivotal.io/runtimes/pks/1-1/installing-nsx-t.html#networking) "For vSphere Cluster Names, enter the name of the vSphere cluster that corresponds to the AZ where you deployed the PKS control plane VM."

These statements appear to be conflicting, and do not accurately reflect what this field is used for. This field is used for validation by nsx-t precheck errand, which checks if all the hosts from the clusters specified in the field are onboarded in NSX. You can specify clusters in the format cluster1,cluster2,cluster3.

Source: https://pivotal.slack.com/archives/C6JEFDLT0/p1532372535000404
VMW Jira: https://jira.eng.vmware.com/browse/PKS-919

**Comment by lparis** [comment]
I will pick this up.

**Comment by mjgutermuth** [comment]
Thanks @lparis! I'm closing this since we've merged your PR with the fix.
