### ISSUE TITLE
Typo in "Cluster Creation Fails" Section of Troubleshooting

### ISSUE THREAD

**Issue by tschwaller** [pivotal-cf/docs-pks#290]
![image](https://user-images.githubusercontent.com/6458940/43450331-caf0aa40-94b2-11e8-941d-c880b6691458.png)
This should be

`bosh -e MY-ENVIRONMENT task TASK-NUMBER`

For example:

`$ bosh -e pks task 23`

`task` and not `tasks`.

**Comment by bentarnoff** [comment]
Thanks, @tschwaller. We're pushing the fix now.
