### ISSUE TITLE
Usage Data Section needs to be reordered

### ISSUE THREAD

**Issue by rjain-pivotal** [pivotal-cf/docs-pks#291]
https://docs.pivotal.io/runtimes/pks/1-1/installing-pks.html#install

The usage data section needs to go all the way at the bottom.

**Comment by mjgutermuth** [comment]
Thanks @rjain-pivotal! The location of this section has been fixed: https://github.com/pivotal-cf/docs-pks/commit/06973c0d8719e45955a0d765447f3ff1fb049c14
