### ISSUE TITLE
Update vSphere screenshots to use web client

### ISSUE THREAD

**Issue by lparis** [pivotal-cf/docs-pks#294]
Working through some of the Pivotal docs, specifically at how to Deploy Ops Manager to vSphere (https://docs.pivotal.io/runtimes/pks/1-1/vsphere-om-deploy.html) all the screenshots are from the vSphere C# client and not the web client!  Should we ask to get this updated?  Whilst the deployment might work now, future versions may not expose all the configuration settings when deploying the OVA through the C# client?

**Comment by lparis** [comment]
I will pick this up. Thanks.

**Comment by bentarnoff** [comment]
Hey @lparis please coordinate with @mjgutermuth on this story. This topic is cloned from our main Ops Manager docs, so if we update the vCenter screenshots we should coordinate with our counterparts to ensure they are also updated in the OM docs. We should also ping the Ops Manager Team to see if they have a view. cc: @mjgutermuth

**Comment by lparis** [comment]
Yes, will do. Thanks.

**Comment by lparis** [comment]
@mjgutermuth I believe I have the screenshots now. I am wondering what the best approach is since these are single sourced from the Ops Mgr docs?

**Comment by bentarnoff** [comment]
Hey @lparis just wanted to follow up on this. Is this still actionable? cc: @mjgutermuth

**Comment by lparis** [comment]
Yes, I am doing it. But I need to follow up with Melinda first. Please keep open as WIP. thanks

**Comment by bentarnoff** [comment]
Hey @lparis just wanted to check whether this is still in flight or if I can close out. Thanks.

**Comment by lparis** [comment]
This is fixed. Closing.
