### ISSUE TITLE
Multiple misleading instructions on this page of vsphere-om-deploy for PKS 1.1

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pks#295]
I am referring to URL: https://docs.pivotal.io/runtimes/pks/1-1/vsphere-om-deploy.html 

Please find below list of issues that need to be addressed on this page.

1. This page does not tell which type of folder needs to be created in the datacenter at step# 5. There are 4 different types of folders that can be created at this step. But, the instruction does not reflect that.

2. There is no file menu as described at step# 7 to select .ova file to upload

3. There is no license agreement step as mentioned at step# 10 in the actual flow

Almost all steps are different from actual flow on vSphere. So, not listing everything here. But this is completely off the actual experience and not very helpful. Please correct this page.

**Comment by lparis** [comment]
WIP https://github.com/pivotal-cf/docs-pks/pull/480

**Comment by lparis** [comment]
Done, see https://github.com/pivotal-cf/docs-pks/pull/480

**Comment by mjgutermuth** [comment]
Thank you @lparis! @parth-pandit, I'm going to close this issue for now, but please let us know if there are additional improvements we need to make to address your concerns.
