### ISSUE TITLE
Recreate VMs step in PKS restore

### ISSUE THREAD

**Issue by jerryhwang72** [pivotal-cf/docs-pks#296]
This part (https://docs.pivotal.io/runtimes/pks/1-1/bbr-restore.html#recreate-vms) is obscure with such short description, especially for PKS customer with no experience with PCF/BBR.

More details can be useful.

1. What VMs exactly to recreate or PKS VM?
If PKS VM, deploy PKS tile and restore with a backup artifact?

2. What if PKS VM still exists, but database corrupted, so I only want to restore mysql database to the existing PKS VM?

3. What'd be the difference of VM preparation like if I have a backup with or without manifest option?

Also in the doc or backup (https://docs.pivotal.io/runtimes/pks/1-1/bbr-backup.html#back-up-deployment), could have a link or more info about "--with-manifest"

**Comment by glestaris** [comment]
hey @jerryhwang72,

We (PCF Platform Recovery and PKS teams) are actively working on a complete B+R experience for PKS. As we make more progress will be updating the PKS documentation accordingly.
