### ISSUE TITLE
GCP Load balancer for the cluster, this has to be separate section

### ISSUE THREAD

**Issue by rjain-pivotal** [pivotal-cf/docs-pks#297]
The A Record for the LB has to be separate section... not to mix with Reconfigure LB

In the sidebar menu, select Cloud DNS.
Select the zone where your load balancer is deployed.
Click Add record set.
Under DNS Name, enter a subdomain for the load balancer. For example, to use my-cluster.example.com as your cluster hostname, enter my-cluster in this field.
Select a Resource Record Type, TTL, and TTL Unit.
Enter the IP address for the master node of the cluster. You located this IP address in the pks cluster output earlier in this procedure.
Click Create.

**Comment by mjgutermuth** [comment]
Thanks @rjain-pivotal! We've updated this section: http://docs.pivotal.io/runtimes/pks/1-1/gcp-cluster-load-balancer.html#reconfigure
