### ISSUE TITLE
pks cli command to login should be replaced

### ISSUE THREAD

**Issue by shausy** [pivotal-cf/docs-pks#304]
In the given document pks cli command given for login is in correct

`pks login -a api.pks.example.com \
--client-name automated-client \
--client-secret randomly-generated-secret -k `

`Error: unknown flag: --client-name
Usage:
  pks login [flags]

Examples:
  pks login -a <API> -u <USERNAME> -p <PASSWORD> [--ca-cert <PATH TO CERT> | -k]

Flags:
  -a, --api string              The PKS API server URI
      --ca-cert string          Path to CA Cert for PKS API
  -h, --help                    help for login
  -p, --password string         Password
  -k, --skip-ssl-verification   Skip SSL Verification
  -u, --username string         Username
`

should be replaced with pks login -a <API> -u <USERNAME> -p <PASSWORD> [--ca-cert <PATH TO CERT> | -k]

**Comment by bentarnoff** [comment]
@shausy Thanks for this. That flag should still work. Is it possible you're using an older version of the PKS CLI? Please download the latest version of the PKS CLI from Pivotal Network using [these instructions](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-1/installing-pks-cli.html) and see if the issue continues.

**Comment by shausy** [comment]
Sure thanks for the info. I will check and update

**Comment by bentarnoff** [comment]
Thanks @shausy. Closing this but feel free to reach out again if you have any more questions or concerns.
