### ISSUE TITLE
Need additional steps before Modify the Ops Manager IAM Role

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#309]
In "Modify the Ops Manager IAM Role": http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-prepare-env.html#om-instance-profile
	3. Select Ops Manager IAM Role for your environment.

https://github.com/pivotal-cf/docs-pks/blob/master/aws-prepare-env.html.md.erb

Need additional steps for Creating the Ops Manager IAM Role first

**Comment by kroberts7** [comment]
Adding: @outofmem0ry

**Comment by bentarnoff** [comment]
Hey @kroberts7 thanks for this. We've worked with @outofmem0ry to reorder the AWS install flow. "Preparing AWS Before Deploying PKS" (https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-prepare-env.html) now comes *after* "Deploying Ops Manager on AWS" and "Configuring Ops Manager on AWS." I believe this change takes care of your concerns. But please let us know if you have any further questions. Thanks again.

**Comment by kroberts7** [comment]
Thanks @bentarnoff . @outofmem0ry and I paired together when discovering this, so all good!  Thanks!
