### ISSUE TITLE
Invalid JSON in Create the Master Node Policy

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#310]
In "Step 1: Create the Master Node Policy" http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-prepare-env.html#master-policy

Issue: the JSON policy shown is invalid.  Backslashes should be removed

Example:

This:
"Action": "s3:\*",

Should be:
"Action": "s3:*",

**Comment by kroberts7** [comment]
Adding: @outofmem0ry

**Comment by bentarnoff** [comment]
Hey @kroberts7 thanks for all these! If you know the change you'd like to see reflected in the topic, please also feel free to submit PRs. Thanks.

**Comment by kroberts7** [comment]
Hi @bentarnoff Yeah, for some (such as these Invalid JSON's) I can do that.  No problem.  I'll get to those later today.  Had an issue with my docs-pks fork earlier.  I'll look later and get back to you.

**Comment by kroberts7** [comment]
@bentarnoff Is it possible that the JSON policies for taken from a pipeline, which could have inserted the `\` chars?

**Comment by kroberts7** [comment]
Hi @bentarnoff Here's the first PR above.
