### ISSUE TITLE
Need confirmation if s3 buckets are required for PKS on AWS

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#312]
In Create the Master Node Policy
http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-prepare-env.html#master-policy

For this section of the Node Policy:

{
          "Effect": "Allow",
          "Action": "s3:\*",
          "Resource": [
              "arn:aws:s3:::kubernetes-\*"
          ]
      },

Can we get dev to confirm if s3 buckets required by the operator? 

Addn'l reference:  docs "Configuring AWS for PCF" and Create s3 Buckets

**Comment by kroberts7** [comment]
Adding: @outofmem0ry

**Comment by bentarnoff** [comment]
Hey @neil-hickey would you be able to speak to the above question?

**Comment by bentarnoff** [comment]
This is blocked on https://www.pivotaltracker.com/story/show/160729059 and https://www.pivotaltracker.com/n/projects/2093412/stories/160098582.

**Comment by animatedmax** [comment]
Hi @kroberts7
We've confirmed that S3 buckets are not required and removed the statement from the documentation set. Thanks!
