### ISSUE TITLE
Deploying Ops Manager on AWS.  Operator will require steps to add those permissions

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#314]
In: 
http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-om-deploy.html#prereqs

The steps should be in Configuring AWS for PCF docs.  Can we have those steps included for adding these permissions to existing/new IAM user.?

**Comment by kroberts7** [comment]
Adding: @outofmem0ry

**Comment by mjgutermuth** [comment]
Thanks @kroberts7! This is a great point. I've moved those steps to the Ops Manager config section: https://github.com/pivotal-cf/docs-pks/commit/b1058dc9b63856fdf3de7e699a899dc06aa43cd9
