### ISSUE TITLE
For AmazonVPCFullAccess permission, No VPC Service found

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#315]
In: 
http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-om-deploy.html#prereqs

Cannot locate this permission in AWS.

**Comment by bentarnoff** [comment]
Hey @neil-hickey would you be able to speak to the above question?

**Comment by bentarnoff** [comment]
Hey @kroberts7 which permission in particular can you not locate?

**Comment by kroberts7** [comment]
Hi @bentarnoff .

In the permission prereq list, for AmazonVPCFullAccess, there is No VPC Service found.

**Comment by neil-hickey** [comment]
<img width="1031" alt="screen shot 2018-08-29 at 16 43 53" src="https://user-images.githubusercontent.com/6075668/44799009-d8822d00-abaa-11e8-97ce-3d950a39d0a1.png">

@kroberts7 @bentarnoff Is this the permission you can't find?

**Comment by kroberts7** [comment]
Hi @neil-hickey Yes it is!  Hmmm, while working with @outofmem0ry we could not find it through his account IAM.  However, when I am using my account IAM, I do see it (attached screenshot from mine).  @outofmem0ry when you get a minute, can you check again?

![amazonvpcfullaccess_screenshot_kroberts](https://user-images.githubusercontent.com/12681013/44805778-fa16f080-ab79-11e8-9b3c-29377019399d.png)

**Comment by bentarnoff** [comment]
Thanks @outofmem0ry, I'll close this. Regarding the Terraform issue, please take a look at https://www.pivotaltracker.com/story/show/160080142.
