### ISSUE TITLE
Ops Manager IAM Role creation steps missing

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#316]
The documentation here assumes that a IAM role for Opsmgr already exists and asks to modify it's permissions - http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-prepare-env.html#om-instance-profile .

Documentation should include steps similar to https://docs.pivotal.io/pivotalcf/1-12/customizing/pcf-aws-manual-config.html#create-iam to configure a role for PKS/Opsmgr.

cc - @kroberts7

**Comment by mjgutermuth** [comment]
Thanks for pointing this out, @outofmem0ry! The OD-PKS team says that the Terraform script that deploys Ops Manager creates this role, so we've reordered the installation topics to reflect this feedback: http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-index.html

Please let us know if there are additional changes we need to make to resolve this. Thanks again!
