### ISSUE TITLE
PAS terraforming files won't work for PKS on AWS

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#317]
Under http://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-om-deploy.html we have directed the users to `Navigate to the Pivotal Application Service (PAS) release on Pivotal Network` and the note states 

```
Note: The AWS Terraform template installs Ops Manager for Pivotal Cloud Foundry (PCF). The template can be used when deploying either PAS or PKS.
``` 

This is not true. Using PAS terraforming files will create objects which are not needed by PKS at all. These objects include extra s3 buckets, load balancers, dns records etc. We can not assume that a user will modify these files to install PKS and ideally a user should not. Either these files should be catered for PKS or a manual install procedure should be detailed in the docs.

cc - @kroberts7

**Comment by bentarnoff** [comment]
Hey @neil-hickey any thoughts on this?

**Comment by mjgutermuth** [comment]
Hi @outofmem0ry do the changes in PR https://github.com/pivotal-cf/docs-pks/pull/422 address the issues you mentioned here? I see that PR removed quite a bit of content but I'm not sure if it's the same content you're referring to.

**Comment by kroberts7** [comment]
Hi @mjgutermuth , Just checking in here.  @outofmem0ry is on PTO for the next 3 weeks.  Did you get the answer(s) you were looking for?

**Comment by bentarnoff** [comment]
Hey @kroberts7! We're currently working with the OD-PKS team to get the new PKS AWS Terraform template documented. The PR that Melinda referenced above includes part of that work but there will be additional PRs to complete it. We hope to have those docs ready for you soon! Thanks.

**Comment by bentarnoff** [comment]
Hey @outofmem0ry @kroberts7 we updated the PKS AWS documentation in collaboration with the OD-PKS Team to make it more accurately reflect the Terraform process: https://docs.pivotal.io/runtimes/pks/1-2/aws-index.html. Closing this for now. Thank you!
