### ISSUE TITLE
PKS v1.1 - Configure Ops Man Document - Create Network Step

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pks#325]
**Document URL:** https://docs.pivotal.io/runtimes/pks/1-1/gcp-om-config.html
**PKS Version:** 1.1
**Problem Section:** Step 5: Create Networks Page
**Problem Description:** The Add Network section of the tile also has a subnet section. The document does not mention anything about it, which is confusing. Also, the subnet section has availability zones to be selected with checkboxes for all of them. The document also does not have any reference to it. Please add these details as it is really confusing in its current format.

**Comment by bentarnoff** [comment]
Thanks @parth-pandit. The PKS v1.1 docs are no longer live, but I believe this issue has been addressed in the PKS v1.2+ docs. For example, https://docs.pivotal.io/pcf/om/2-3/gcp/config-manual.html. Closing.
