### ISSUE TITLE
Confusing Examples for LDAP / OIDC Auth

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#340]
wrt to manage-users.html.erb

The base example on line 186 is decent, but then the concrete example on line 212 uses roleRefs rather than rules.   This is confusing.  We should include 2-3 examples that use rules, and 2-3 examples that use roleRefs.

**Comment by bentarnoff** [comment]
Thanks for the feedback, @mcowger. 

@nikitarathi23 I believe you authored the original content in the section of https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/manage-users.html that Matt is referring to. Would you be able to speak to Matt's concerns?

**Comment by neil-hickey** [comment]
hi @mcowger we reached out, but didn't get a response. Could you help us understand if this is still a problem?

**Comment by mcowger** [comment]
I've re-read the examples, and it looks like they've been updated and seem reasonable.  Will close.
