### ISSUE TITLE
Confusing REPLACEMENT terminology

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#341]
referring to https://github.com/pivotal-cf/docs-pks/blob/master/manage-users.html.md.erb

In many of the examples (including, but not limited to line 212), we use ALL-CAPS-TO-SIGNIFY-TOKEN-REPLACEMENT.

We should use more the standard <TOKEN> or [TOKEN].

**Comment by bentarnoff** [comment]
Hey @mcowger thanks for this. The style guide that we follow throughout the PCF documentation specifies placeholder text in ALL-CAPS with dashes between words, but no square brackets. So I believe the placeholder text in this topic conforms to our style guide. 

Thanks for reaching out, and feel free to reach out again if you have further questions or concerns.

**Comment by mcowger** [comment]
Fair enough - I'd argue the style guide should be changed, but I'll take that up elsewhere.
