### ISSUE TITLE
backup-cleanup

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#342]
The command line on 283 says 'backup-cleanup'

1. That term doesn't not exist in the actual command.  Why is it called that?

**Comment by animatedmax** [comment]
Can you help us by pointing to the page you were referring to?

The only place I see that we use the term `backup-cleanup` is in the [Clean Up after a Failed Backup](https://docs.pivotal.io/runtimes/pks/1-1/bbr-backup.html#manual-clean) section of the _Back Up the PKS Control Plane_ topic.

In this topic we refer to the command `BOSH_CLIENT_SECRET=BOSH-CLIENT-SECRET bbr deployment --target BOSH-TARGET --username BOSH-CLIENT --deployment DEPLOYMENT-NAME --ca-cert PATH-TO-BOSH-CA-CERT backup-cleanup`.

This command does contain the term `backup-cleanup`, so I'm not sure where we need to look. Thanks for your help in identifying the location of this issue.

**Comment by mcowger** [comment]
It looks like this was corrected in commit hash 0ba7d660605ecd9559111d565a39660ea7e9916d
