### ISSUE TITLE
Generating Certificates Pages needs updates

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pks#351]
generate-certificates.html.md.erb

For generating the CA Certs, there are issues in step 2 and step 4.

Step 2 - the template and example don't match, the CN appears to be an IP address but is shown as a hostname
Step 4 - does the command to generate the certificate need to include the SAN part if it is in the template?

Basically we should re-do this section and ensure it is correct.

**Comment by mjgutermuth** [comment]
Hi @agregory999 thanks for this feedback! We believe this PR addresses the issues you mentioned: https://github.com/pivotal-cf/docs-pks/pull/379

Please let us know if you have additional feedback. Thanks again!
