### ISSUE TITLE
Misleading calculation on vm-sizing.html page

### ISSUE THREAD

**Issue by tschwaller** [pivotal-cf/docs-pks#352]
The following callucation is misleading:

Minimum number of workers [W] = p / 110
Minimum RAM per worker = m * p/W
Minimum number of CPUs per worker = c * p/W

(using Number of pods [p], RAM per pod [m], CPU per pod [c])

I would change that to
Minimum RAM per worker = m * 110
Minimum number of CPUs per worker = c * 110

because p/W = p/(p/110) = 110.

The example shows that you get too small number for RAM and CPU when you increase the number of worker nodes in the first step.

Calculate the number of workers using p / 110:  1000/110 = 9.09 ~= 10 workers
Calculate the minimum RAM per worker using m * p/W:  1 * 1000/10 = **100 GB**
Calculate the minimum number of CPUs per worker using c * p/W: 0.10 * 1000/10 = **10 CPUs**

If you use just 110 instead of p/W you get:
Calculate the minimum RAM per worker using m * p/W:  1 * 110 = **110 GB**
Calculate the minimum number of CPUs per worker using c * 110: 0.10 * 110 = **11 CPUs**

**Comment by bentarnoff** [comment]
Hey @tschwaller thanks for this. I've updated https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/vm-sizing.html#worker-sizing to reflect your recommendation. Can you take a look and tell me what you think? Then I can bring these changes into the PKS v1.0 and PKS v1.1 docs as well.

**Comment by tschwaller** [comment]
Looks good now. When checking the officially supported max. numbers of Kubernetes 1.11 at
https://kubernetes.io/docs/setup/cluster-large/#support

<img width="828" alt="image" src="https://user-images.githubusercontent.com/6458940/46064271-4b150700-c16f-11e8-8dd8-e6f257bb706b.png">

I realized that Kubernetes 1.11 supports "No more than 100 pods per node". So maybe we should reduce the number 110 in the docs also to 100. Is there a reason why we used 10 more in our documentation?

**Comment by bentarnoff** [comment]
Hey @tschwaller thanks for this. Great catch on the maximum 100 pods per node. I'm not sure what the reasoning was for the use of 110 in our doc, but I've updated it throughout to reflect the accurate figure: https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/vm-sizing.html#worker-sizing. I've also brought this change into the PKS v1.1 docs. 

Please let me know if you have any further thoughts on this front. Otherwise, I can close the issue. Thanks.
