### ISSUE TITLE
Incorrect statements about persistent volumes and multi-AZ deployments

### ISSUE THREAD

**Issue by embano1** [pivotal-cf/docs-pks#365]
Hi,

Just wanted to bring this to your attention:

https://github.com/pivotal-cf/docs-pks/blob/794ad0b853588da346c7b89eeb133af656db4217/maintain-uptime.html.md.erb#L131

This is not correct, PVs (depending on the underlying storage type) are either completely free of zonal information or can have multiple zone labels attached. Both potentially allows a PV to travel between AZs.

https://github.com/pivotal-cf/docs-pks/blob/794ad0b853588da346c7b89eeb133af656db4217/maintain-uptime.html.md.erb#L132

This is not correct, as since K8s v1.11 this admission controller is disabled and even PKS jobs explicitly disable it: https://github.com/pivotal-cf/pks-kubo-release/blob/f3f04f97d9ef08ba2a4781ac736f6cb15f240468/jobs/kube-apiserver/templates/config/bpm.yml.erb#L43

Looks like this whole paragraph needs a rewrite. Also, it is worth making the distinction between static and dynamic volume provisioning (incl. capabilities of the underlying cloud providers, e.g. vSphere, GCP and AWS for PKS v1.2).

**Comment by mjgutermuth** [comment]
@skelly-pivotal ^^

**Comment by mjgutermuth** [comment]
Thanks @embano1! PR https://github.com/pivotal-cf/docs-pks/pull/373 updates these lines. I'm going to close this issue, but please let us know if you see additional feedback!
