### ISSUE TITLE
Clearer step and terraform command for SSH Private Key in AWS Config Page.

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#374]
During `Configuring Ops Manager on AWS`,  the step on [SSH Private Key](https://github.com/pivotal-cf/docs-pks/blob/master/aws-om-config.html.md.erb#L118) 

Should match what we have in [PCF for AWS and SSH Private Key
](https://github.com/pivotal-cf/docs-pcf-install/blob/master/aws-om-config-terraform.html.md.erb#L76)

CC: @outofmem0ry

**Comment by seviet** [comment]
hey @kroberts7 -- this has been fixed here https://docs.pivotal.io/runtimes/pks/1-2/aws-om-config.html#aws-config
