### ISSUE TITLE
Incorrect AWS User Name

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#383]
https://docs.pivotal.io/runtimes/pks/1-2/aws-prepare-env.html#om-user

The docs states "YOUR-ENVIRONMENT-NAME_ops_manager_user" is the user to be edited, but the actual user name is YOUR-ENVIRONMENT-NAME_om_user

**Comment by seviet** [comment]
hey @mcowger -- this has been fixed. see https://docs.pivotal.io/runtimes/pks/1-2/aws-prepare-env.html#om-user -- thanks!
