### ISSUE TITLE
Code/JSON Samples Should have a 'copy' button

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#384]
All code / JSON samples should have a copy button, ala what everyone else does:

Take a look at: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-create-vnet-classic-cli

![screen shot 2018-10-02 at 2 47 19 pm](https://user-images.githubusercontent.com/1929548/46378946-1ebb2800-c652-11e8-9694-ccf51f54a955.png)

**Comment by animatedmax** [comment]
Thank you for providing this suggestion, and I will pass it along to our publication tools team.
