### ISSUE TITLE
"management" network name changed to "infrastructure" network

### ISSUE THREAD

**Issue by dkalemba** [pivotal-cf/docs-pks#406]
i believe that the pks terraform release 0.21.0 changed the name of the management network to infrastructure network...

https://github.com/pivotal-cf/terraforming-aws/releases/tag/v0.21.0

https://github.com/pivotal-cf/docs-pks/blob/fcbc930f836bb34bb8357f2ef996f4f9eddc5c49/aws-om-config.html.md.erb#L228

**Comment by bentarnoff** [comment]
Thanks @dkalemba. We've updated the ["Configuring Ops Manager on AWS"](https://docs.pivotal.io/runtimes/pks/1-2/aws-om-config.html#om-networks) topic to address this.
