### ISSUE TITLE
"pas" network is actually "pks" network in terraform output

### ISSUE THREAD

**Issue by dkalemba** [pivotal-cf/docs-pks#408]
in release 0.21.0 of the terraform scripts, the pas subnet is now labeled pks subnet

https://github.com/pivotal-cf/terraforming-aws/releases/tag/v0.21.0

https://github.com/pivotal-cf/docs-pks/blob/fcbc930f836bb34bb8357f2ef996f4f9eddc5c49/aws-om-config.html.md.erb#L324

**Comment by bentarnoff** [comment]
Thanks @dkalemba. We've updated the ["Configuring Ops Manager on AWS"](https://docs.pivotal.io/runtimes/pks/1-2/aws-om-config.html#om-networks) topic accordingly.
