### ISSUE TITLE
ClusterSink Resource not found after upgrade to 1.2.1

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-pks#460]
CC: @ahevenor 

After upgrading to PKS 1.2.1, the ClusterSink resource is missing for clustersinks.apps.pivotal.io

We discovered while packaging the clustersink that opsman only executes add on spec jobs when a unique name is used. We addressed this eventually but have on confirmed that 1.2.1-build.9 uses the same name as previous tiles and therefore ends up not getting the clusterSink (but would on a fresh install). the final RC and GA versions address this problem

**Workaround**
I am having the following public-facing KB article published:
https://community.pivotal.io/s/article/ClusterSink-Resource-not-found-after-upgrade

**Request**
We would like to have this mentioned in 
- Known Issues 
https://docs.pivotal.io/runtimes/pks/1-2/release-notes.html#v1.2.1-known-issues
- Creating Sink Resources
https://docs.pivotal.io/runtimes/pks/1-2/create-sinks.html

**Comment by mjgutermuth** [comment]
Thanks for calling this out, @kroberts7! We've updated the docs with this info in the two locations you mentioned: 

- https://docs.pivotal.io/runtimes/pks/1-2/release-notes.html#v1.2.1-known-issues
- https://docs.pivotal.io/runtimes/pks/1-2/create-sinks.html#define-cluster-sink
