### ISSUE TITLE
installing bitnami project (Kubeapps) connection refused mongodb://127.0.0.1:27017

### ISSUE THREAD

**Issue by abhilash07** [pivotal-cf/docs-pks#477]
hi i have deployed pks on gcp 
OPS-Manager Version = pcf-gcp-2.2-build.380
PKS Version = pivotal-container-service-1.2.4-build.6

Name:                     my-cluster
Plan Name:                small
UUID:                     2da063db-7061-4299-80e4-b6f16f41f3d9
Last Action:              CREATE
Last Action State:        succeeded
Last Action Description:  Instance provisioning completed
Kubernetes Master Host:   xxxxxxx
Kubernetes Master Port:   8443
Worker Nodes:             3
Kubernetes Master IP(s):  xxxxxx
Network Profile Name:

triller = v2.10.0
helm = Client = v2.9.1 , Server = v2.10.0
now i am trying to deploy bitnami product kubeapps using helm but i am getting below error. Especially in bitnami mongodb

![screen shot 2018-12-13 at 10 03 30 am](https://user-images.githubusercontent.com/10971841/49908704-281d0800-febf-11e8-8c7f-1797864a71cf.png)

the same error is applying when i deployed opensource project kubo. I don't know why, did anyone know how to solve this issue.

below i upload bitname-kubeapps-mongodb pod logs for your reference

[logs-from-kubeapps-mongodb-in-kubeapps-mongodb-54b74f7689-94lzl.txt](https://github.com/pivotal-cf/docs-pks/files/2674149/logs-from-kubeapps-mongodb-in-kubeapps-mongodb-54b74f7689-94lzl.txt)
![screen shot 2018-12-13 at 10 14 43 am](https://user-images.githubusercontent.com/10971841/49908912-f7899e00-febf-11e8-8341-7420d3d29785.png)

Thanks in advance

**Comment by bentarnoff** [comment]
Thanks, @abhilash07. @skelly-pivotal would you or someone on your team be able to speak to the above? Thanks!

**Comment by bentarnoff** [comment]
@ryanjjones10 @virtmerlin Any thoughts on the above?

**Comment by animatedmax** [comment]
Hi @abhilash07 I am closing this because it is not a documentation issue. If you are still having a problem, please raise an issue in an engineering repository. Thanks!
