### ISSUE TITLE
PVC section should include the annotations about creating a default storage class.

### ISSUE THREAD

**Issue by JasonMorgan** [pivotal-cf/docs-pks#482]
At least one example on this page should include the annotation for setting the default storage class on a kube cluster:

```
annotations:
  storageclass.kubernetes.io/is-default-class: "true"
```

That and maybe make a note about why we need to set the default storage class. I'm happy to update the docs myself, just wanted to make sure there was an issue to track it.

**Comment by lparis** [comment]
I have updated this PR to address this issue: https://github.com/pivotal-cf/docs-pks/pull/536.

**Comment by lparis** [comment]
This is addressed: https://docs.pivotal.io/runtimes/pks/1-3/volumes.html#default-storage-class. Closing.
