### ISSUE TITLE
Invalid JSON np_customer_B.json example 

### ISSUE THREAD

**Issue by sudhindrarao** [pivotal-cf/docs-pks#515]
np_customer_B.json json snippet has invalid syntax.  

1. Missing quotes around  value for  "pod_routable": enabled,
2. Pod IP block has missing comma   "pod_ip_block_ids": [
            "ebe78a74-a5d5-4dde-ba76-9cf4067eee55",
            "ebe78a74-a5d5-4dde-ba76-9cf4067eee56"
        ]

So, example should be like this

np_customer_B.json
{
    "name": "np-cust-b",
    "description": "Network Profile for Customer B",
    "parameters": {
        "lb_size": "medium",
        "t0_router_id": "5a7a82b2-37e2-4d73-9cb1-97a8329e1a92",
        "fip_pool_ids": [
            "e50e8f6e-1a7a-45dc-ad49-3a607baa7fa2"
        ],
        "pod_routable": "enabled",
        "pod_ip_block_ids": [
            "ebe78a74-a5d5-4dde-ba76-9cf4067eee55",
            "ebe78a74-a5d5-4dde-ba76-9cf4067eee56"
        ],
        "master_vms_nsgroup_id": "9b8d535a-d3b6-4735-9fd0-56305c4a5292",
        "pod_subnet_prefix" : 26
    }
}

**Comment by lparis** [comment]
This is fixed. See https://docs.pivotal.io/runtimes/pks/1-3/network-profiles-define.html.

**Comment by bentarnoff** [comment]
Thanks @lparis. Closing.
