### ISSUE TITLE
Datastore Name

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pks#520]
For the datastore name, if a deployment has multiple vSphere AZs defined, each with a DS, shoould we configure this with a comma separated list, and have it mirror what is on the director tile?  For example, if there are 3 AZs and the Bosh tile has DS_AZ1,DS_AZ2,DS_AZ3, then should the Kubernetes API/Datastore read as the same?  Please document best practices.

**Comment by bentarnoff** [comment]
Thanks @agregory999. @skelly-pivotal @ryanjjones10 Could you speak to the above question? Thank you.

**Comment by skelly-pivotal** [comment]
Adding @virtmerlin who is currently PM'ing PKS with @ryanjjones10

**Comment by virtmerlin** [comment]
Adding @lparis to resolve in the doc.

@agregory999 ... I assume u are referring to the 'Datastore Name` field in the Kubernetes Cloud Provider config of the PKS tile for vSphere.  That field is intended as a single datastore that would be leveraged if the K8s StorageClass did not define a Datastore/Tag/StoragePolicy.   The field should NOT include a csv list of BOSH Job/VMDK datastores, but simply be the default target.  In a case w multi AZ,  we should require StorageClasses to define specific datastores until we support allowed_topologies

https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html
https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
