### ISSUE TITLE
Harbor marked as "Not Available" for IaaS other than vSphere

### ISSUE THREAD

**Issue by bstick12** [pivotal-cf/docs-pks#523]
On https://docs.pivotal.io/runtimes/pks/1-3/#preparing Harbor integration is marked as "Not Available" for all IaaSes other than vSphere. I don't believe the tile is limited to vSphere.

Can we respond to this Twitter request if the documentation is incorrect -https://twitter.com/cfurmaniak/status/1086184351157706752?s=19

**Comment by bentarnoff** [comment]
Thanks @bstick12. Please see the updated topic at https://docs.pivotal.io/runtimes/pks/1-3/index.html#preparing.

**Comment by bstick12** [comment]
@bentarnoff It is still marked as "Not Available" for Azure. Also this change should be backported to the 1.2.x and perhaps the 1.1.x versions of the releases notes

**Comment by bentarnoff** [comment]
Thanks @bstick12. 

Hey @lparis, is there a reason why you didn't mark Harbor as "Available" for Azure in your recent PR?

Also, @lparis, can I ask you to backport these changes to the `1.2` and `1.1` branches, per Brendan's request above? Thank you!

**Comment by lparis** [comment]
So, based on my face-to-face discussion with the Harbor PM, James Zabala, last week, the response to my question on Harbor-Azure support was that it did not "clear our pipeline." I do not have an Azure env so I cannot try it myself. I put this comment in the PR. I will port the changes to the 1.2 and 1.1 branches.

**Comment by lparis** [comment]
Fixes merged. Email sent to PM. Closing. Thanks.
