### ISSUE TITLE
Docs insist on a wildcard certificate 

### ISSUE THREAD

**Issue by svrc-pivotal** [pivotal-cf/docs-pks#525]
Good day, all of the install documentation from here:

https://github.com/pivotal-cf/docs-pks/blob/master/_pks-api.html.md.erb#L20

Insists that the PKS API requires a wildcard certificate.   It does not.   I've created several environments on several clouds (vSphere, GCP, Azure) with PKS 1.2 and PKS 1.3, with Ops Manager 2.3 and 2.4, with just a standard FQDN.   

I believe this stems from older Ops Man tile metadata that did require a wildcard certificate in this textbox, (or perhaps an Ops Man limitation), but this was a bug, not a requirement.

**Comment by bentarnoff** [comment]
Thanks @svrc-pivotal. I've updated that partial accordingly. You can see the updated version on the staging site, for instance at https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/installing-pks-aws.html#pks-api.
