### ISSUE TITLE
PKS 1.3: "Using dynamic PV" page is missing Azure Storage Classes

### ISSUE THREAD

**Issue by npintaux** [pivotal-cf/docs-pks#526]
"Using Dynamic Persistent Volumes" page currently lists AWS, GCP, vSphere, but is missing Azure file and disk storages:
- File Storage class: 
       - doc: https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file
       - repo: https://github.com/cloudfoundry-incubator/kubo-ci/blob/master/specs/storage-class-azure-file.yml
- Disk Storage class: 
       - doc: https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk
       - repo: https://github.com/cloudfoundry-incubator/kubo-ci/blob/master/specs/storage-class-azure.yml

**Comment by lparis** [comment]
This PR adds the Azure storage class: https://github.com/pivotal-cf/docs-pks/pull/536.

**Comment by seviet** [comment]
thank you @npintaux -- we added both Azure storage classes you mention above.
