### ISSUE TITLE
"Using Dynamic PersistentVolumes" should not link to manifests from kubo-ci

### ISSUE THREAD

**Issue by tvs** [pivotal-cf/docs-pks#537]
The [Using Dynamic PersistentVolumes](https://docs.pivotal.io/runtimes/pks/1-3/volumes.html) page references storage class manifests from [cloudfoundry-incubator/kubo-ci](https://github.com/cloudfoundry-incubator/kubo-ci/).

There are two problems here:

* It's referencing the `master` branch, which is a development branch for CFCR's CI. PKS ships locked versions of CFCR (e.g. PKS 1.2 is on CFCR v0.21, PKS 1.3 is on CFCR v0.25) that will consistently lag behind the version that CI's `master` branch is intended for.
* kubo-ci isn't intended as a customer-facing interface - the files in that repo are in no way recommended, they're simply used to test basic functionality. Any sort of recommendations should be curated, tested, and officially supported.

**Comment by seviet** [comment]
@bstick12 is there any chance these files could be made available in a public repo somewhere? we may solve this temporarily by copying in the yml to docs but are worried about accuracy/maintainability. perhaps if we had both options available to the reader....

**Comment by bstick12** [comment]
@seviet I think that as @tvs their is more required of this change that just providing a new location for the storage-class files. I'll open a defect in the PKS-Core backlog linked to this issue. I think that just having an example of the storage-class embedded in the documentation  for each IaaS would be better than serving the file from a new location.

**Comment by bstick12** [comment]
Added https://www.pivotaltracker.com/story/show/163585623

**Comment by animatedmax** [comment]
Since this has been added to the PKS Core Tracker project, I am closing this issue.
