### ISSUE TITLE
javascript error in published docs

### ISSUE THREAD

**Issue by jldec** [pivotal-cf/docs-pks#646]
![Screen Shot 2019-05-02 at 10 02 51 AM](https://user-images.githubusercontent.com/849592/57065740-4c3c8280-6cc2-11e9-9e6e-f0b3eabddebc.png)

**Comment by jldec** [comment]
noticed the same issue in https://github.com/pivotal-cf/docs-pfs/issues/145

**Comment by animatedmax** [comment]
Hi @jldec This issue should now be resolved. Thank you for bringing it to our attention.
![pks](https://user-images.githubusercontent.com/5789726/57092872-472b0380-6cc1-11e9-94e7-150d49104d42.png)
