### ISSUE TITLE
Incorrect Screenshot for Certificate Import

### ISSUE THREAD

**Issue by sgrman** [pivotal-cf/docs-pks#651]
The screen shot for importing into NSX 2.4.0.1 is incorrect.  I have attached the correct screenshot here.  Also, there should be a direction to turn off the "Service Certificate" Option.
<img width="594" alt="Screen Shot 2019-05-07 at 08 26 16" src="https://user-images.githubusercontent.com/19333241/57304736-808ab700-70a5-11e9-8331-6a40a8704889.png">

**Comment by lparis** [comment]
https://github.com/pivotal-cf/docs-pks/pull/654

**Comment by lparis** [comment]
this if fixed, thanks for reporting this

**Comment by agregory999** [comment]
Also perhaps appending -NEW to the name is meaningless.  If it is the New VIP cert, why not call it VIP-CERT
