### ISSUE TITLE
Disable "Service Certificate" when importing NSX certificate?

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#656]
Currently in https://docs.vmware.com/en/VMware-Enterprise-PKS/1.4/vmware-enterprise-pks-14/GUID-generate-nsx-ca-cert-24.html the screenshot shows the "Service Certificate" toggle enabled. I believe this should be disabled. Please seek correct configuration. 

Either way, toggled on or off, add text to doc informing same.

**Comment by lparis** [comment]
https://github.com/pivotal-cf/docs-pks/pull/662
