### ISSUE TITLE
Release notes don't cover vSphere versions when using flannel

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#659]
Update release notes to include vSphere version for when using flannel. Today only covers NSX-T

**Comment by lparis** [comment]
Keith, we now reference the VMware Product Interoperability Matrices for vSphere versions. This is the source of truth that GSS uses and that we will reference. See https://github.com/pivotal-cf/docs-pks/pull/661. Thanks.
