### ISSUE TITLE
contradictory explanation of DenyEscalatingExec

### ISSUE THREAD

**Issue by jldec** [pivotal-cf/docs-pks#664]
in https://docs.pivotal.io/runtimes/pks/1-4/deny-escalating-execution.html

> If checked (enabled), the DenyEscalatingExec admission controller will be enabled. Clusters in this plan can then create security vulnerabilities. By selecting the checkbox you are making Kubernetes clusters deployed with this plan insecure.

:point_up: that statement seems contradictory because i believe the admission controller restricts exec and attach commands, so enabling should make the cluster _more_ secure.

**Comment by lparis** [comment]
This is fixed. Closing.

**Comment by lparis** [comment]
https://docs.pivotal.io/runtimes/pks/1-4/deny-escalating-execution.html
