### ISSUE TITLE
Links to Reserved IP Blocks, node and pod IP blocks and plan IP blocks not working

### ISSUE THREAD

**Issue by rotbau** [pivotal-cf/docs-pks#676]
**What Happened:**
Clicking on the links in the paragraph below on this Pivotal webpage does not open anchors or links to node networks, pod networks, Plan IP Blocks or Reserved IP Blocks. 

https://docs.pivotal.io/runtimes/pks/1-4/nsxt-create-objects.html

`Create separate NSX-T IP Blocks for the node networks and the pod networks. The subnets for both nodes and pods should have a size of 256 (/16). For more information, see Plan IP Blocks and Reserved IP Blocks.`

**What I expected to Happen:**

Taken to sections of the document describing items or external pages describing those items.  Especially import is the Reserved IP Blocks.  Something similar to what is listed at this link.
https://docs.vmware.com/en/VMware-Enterprise-PKS/1.3/vmware-enterprise-pks-13/GUID-nsxt-prepare-env.html

**Browsers Tested:**

Google Chrome Version 74.0.3729.169 (Official Build) (64-bit) on Mac
Safari Version 12.1.1 (13607.2.6.1.2)

Links appear not functional in versions 1.2 and 1.3 of this document as well.

**Comment by seviet** [comment]
This has been fixed! Thank you for reporting this.
