### ISSUE TITLE
Document the process of the public key generation and the exact format to use in the field during deployment of OpsMan OVA

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#696]
Opening on behalf of Hany Michael

"It would be also great to document the process of the public key generation and the exact format to use in the OpsMan field during deployment of the OpsMan OVA, etc. As far as I have searched the public docs, there is no details around this."

**Comment by lparis** [comment]
Keith, this is in progress as a KB article. Will be sharing the KB separately. Thanks. Closing.
