### ISSUE TITLE
Corrections to "Import the New Certificate to NSX Manager" section of https://docs.pivotal.io/pks/1-4/generate-nsx-ca-cert-24.html 

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#726]
Corrections to **Import the New Certificate to NSX Manager** section of https://docs.pivotal.io/pks/1-4/generate-nsx-ca-cert-24.html 

- Change "Navigate to System > Trust > Certificates" to "Navigate to System > Certificates"
- Change "Click Save" to "Click Import"
- Put note regards "Service Certificate" before step 3 (Click Save) as could be missed or noticed too late.

**Comment by lparis** [comment]
This is addressed in the 1.5 docs here: http://docs-pcf-staging.cfapps.io/pks/1-5/vsphere-nsxt-index.html. We will backport the appropriate topics including this one to the 1.4 branch when 1.5 is out or nearly out. Thanks.
