### ISSUE TITLE
Gear2: Directory /opt/vmware/scripts/nsx/ called out in troubleshooting doesnt exist

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#747]
Using latest gear2 beta pks-v0.9.0-dev.comprehensive-ova.master.480179-d77c92b7 the directory /opt/vmware/scripts/nsx/ as per http://docs-pcf-staging.cfapps.io/pks/1-5/console/console-troubleshooting.html does not exist. Please follow up with eng if script has been removed or resides elsewhere or is due in a future build. Thank you

**Comment by lparis** [comment]
Keith, post this feedback here please: https://jira.eng.vmware.com/browse/PKS-2446. This is the consolidated place for Gear2 feedback.
