### ISSUE TITLE
Upgrade preparation checklist gives Azure-only instructions

### ISSUE THREAD

**Issue by dtimm** [pivotal-cf/docs-pks#804]
In the below section, there are instructions for resolving a VM issue using the Azure CLI, but not in vSphere, GCP, or AWS:
https://github.com/pivotal-cf/docs-pks/blob/38794ddce6c9d9e71f3e13b68be7fc9b9d3daaf4/checklist.html.md.erb#L253-L275

Does this only apply to Azure and not other IaaSes?

**Comment by pspinrad** [comment]
Thanks @dtimm -- good point.  We reworded this to make clear up top that it's an Azure-only step https://docs.pivotal.io/pks/1-6/checklist.html#update-azure-worker-role
