### ISSUE TITLE
API guide for configuring NSX

### ISSUE THREAD

**Issue by zvikaga** [pivotal-cf/docs-pks#821]
Hi, I'm trying to automate the whole process of PKS deployment including the NSX part.
I''m facing some issues with the API guide of VMWARE which does not behave the same as the GUI based guide.
Do you have instructions how to do the same NSX related tasks using NSX's API guide?

Thanks

**Comment by lparis** [comment]
Sorry, we don't have that. Please refer to the NSX API documentation here: https://code.vmware.com/apis/547/nsx-t. Thanks.
