### ISSUE TITLE
Azure and NSX-T 

### ISSUE THREAD

**Issue by mgbrodi** [pivotal-cf/docs-pks#833]
I've noticed that in the Azure docs (https://docs.pivotal.io/pks/1-5/installing-pks-azure.html et similia) there are a couple of mentions to NSX-T:
- Note: If you install Enterprise PKS in an NSX-T environment, we recommend that you select a Worker VM Type with a minimum disk size of 16 GB. The disk space provided by the default medium Worker VM Type is insufficient for Enterprise PKS with NSX-T.
- VMware vRealize Operations Management Pack for Container Monitoring
If you are using Enterprise PKS on vSphere or vSphere with NSX-T Data Center, you can monitor...

Should these be removed?

**Comment by animatedmax** [comment]
Hi @mgbrodi We have removed the NSX-T references. Thank you for alerting us to this issue.
