### ISSUE TITLE
Incorrect steps for retrieving and saving BOSH Director credentials

### ISSUE THREAD

**Issue by johannstander** [pivotal-cf/docs-pks#994]
Under " Ops Manager Installation Dashboard
To retrieve your BOSH Director credentials using the Ops Manager Installation Dashboard, perform the following steps:"

Step 6 current states: "Copy the value of the private_key_pem field.", this is incorrect and should be the following "Copy the password".     There is no private key to download.

This copy process is also mentioned under API retrieval and should be updated.

The "Save the BOSH Director Credentials to a File" is not necessary since this is just a copy of the password value.

**Comment by pspinrad** [comment]
Thanks @johannstander -- fix staged; will go live next push to docs.pivotal.io https://docs-pcf-staging.cfapps.io/pks/1-6/bbr-backup.html#bosh-creds
